- Gather two datasets - successfully extract data using two different data gathering methods and combine the data.
- Assess the data according to quality and tidiness metrics, identifying missing data.
- Clean the data to solve the issues found in the assessing step.
- Update the data store with the cleaned data.
- Produce visualizations on the cleaned data, and answer a brief research question on the dataset.

#### Problem Statement

In 2-4 sentences, explain the problem you want to look at and the datasets you will be wrangling for this project.

Finding the right datasets can be time-consuming. Here we provide you with a list of websites to start with. But we encourage you to explore more websites and find the data that interests you.

#### Gather at least two datasets using two different data-gathering methods

Options: 

- Download data manually
- Programmatically downloading files
- Gather data by accessing APIs
- Gather and extract data from HTML files using BeautifulSoup
- Extract data from a SQL database

In [ ]:
# Downloaded data from kaggle via CSV

import kagglehub

# Download latest version
path = kagglehub.dataset_download("tobycrabtree/nfl-scores-and-betting-data")

print("Path to dataset files:", path)

Downloading from https://www.kaggle.com/api/v1/datasets/download/tobycrabtree/nfl-scores-and-betting-data?dataset_version_number=71...

100%|██████████| 249k/249k [00:00<00:00, 6.55MB/s]

Extracting files...
Path to dataset files: C:\Users\jseidl\.cache\kagglehub\datasets\tobycrabtree\nfl-scores-and-betting-data\versions\71

In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns

In [2]:
scores_bets = pd.read_csv('NFLScore.csv')

In [3]:
scores_bets.head()

,schedule_date,schedule_season,schedule_week,schedule_playoff,team_home,score_home,score_away,team_away,team_favorite_id,spread_favorite,over_under_line,stadium,stadium_neutral,weather_temperature,weather_wind_mph,weather_humidity,weather_detail
0,9/2/1966,1966,1,False,Miami Dolphins,14.0,23.0,Oakland Raiders,NaN,NaN,NaN,Orange Bowl,False,83.0,6.0,71.0,NaN
1,9/3/1966,1966,1,False,Houston Oilers,45.0,7.0,Denver Broncos,NaN,NaN,NaN,Rice Stadium,False,81.0,7.0,70.0,NaN
2,9/4/1966,1966,1,False,San Diego Chargers,27.0,7.0,Buffalo Bills,NaN,NaN,NaN,Balboa Stadium,False,70.0,7.0,82.0,NaN
3,9/9/1966,1966,2,False,Miami Dolphins,14.0,19.0,New York Jets,NaN,NaN,NaN,Orange Bowl,False,82.0,11.0,78.0,NaN
4,9/10/1966,1966,1,False,Green Bay Packers,24.0,3.0,Baltimore Colts,NaN,NaN,NaN,Lambeau Field,False,64.0,8.0,62.0,NaN

In [6]:
import requests 
import json
import secrets

In [13]:
url = 'https://api.sportsdata.io/v3/nfl/scores/json/Schedules/%7B2025%7D?key=449cf530965d4cb69fa1e59dd148234c'

In [16]:
response = requests.get(url)
data = response.json()

In [17]:
data

[{'GameKey': '202510126',
  'SeasonType': 1,
  'Season': 2025,
  'Week': 1,
  'Date': '2025-09-04T20:20:00',
  'AwayTeam': 'DAL',
  'HomeTeam': 'PHI',
  'Channel': 'NBC',
  'PointSpread': -6.0,
  'OverUnder': 47.5,
  'StadiumID': 18,
  'Canceled': False,
  'GeoLat': None,
  'GeoLong': None,
  'ForecastTempLow': 65,
  'ForecastTempHigh': 68,
  'ForecastDescription': 'Light Rain',
  'ForecastWindChill': 68,
  'ForecastWindSpeed': 4,
  'AwayTeamMoneyLine': 260,
  'HomeTeamMoneyLine': -328,
  'Day': '2025-09-04T00:00:00',
  'DateTime': '2025-09-04T20:20:00',
  'GlobalGameID': 19039,
  'GlobalAwayTeamID': 9,
  'GlobalHomeTeamID': 26,
  'ScoreID': 19039,
  'Status': 'Final',
  'IsClosed': None,
  'DateTimeUTC': '2025-09-05T00:20:00',
  'StadiumDetails': {'StadiumID': 18,
   'Name': 'Lincoln Financial Field',
   'City': 'Philadelphia',
   'State': 'PA',
   'Country': 'USA',
   'Capacity': 67594,
   'PlayingSurface': 'Grass',
   'GeoLat': 39.900833,
   'GeoLong': -75.167469,
   'Type': 'Outdoor'}},
 {'GameKey': '202510129',
  'SeasonType': 1,
  'Season': 2025,
  'Week': 1,
  'Date': '2025-09-05T20:00:00',
  'AwayTeam': 'KC',
  'HomeTeam': 'LAC',
  'Channel': 'YT',
  'PointSpread': 1.7,
  'OverUnder': 47.5,
  'StadiumID': 87,
  'Canceled': False,
  'GeoLat': None,
  'GeoLong': None,
  'ForecastTempLow': 57,
  'ForecastTempHigh': 60,
  'ForecastDescription': 'Overcast Clouds',
  'ForecastWindChill': 60,
  'ForecastWindSpeed': 9,
  'AwayTeamMoneyLine': -131,
  'HomeTeamMoneyLine': 111,
  'Day': '2025-09-05T00:00:00',
  'DateTime': '2025-09-05T20:00:00',
  'GlobalGameID': 19054,
  'GlobalAwayTeamID': 16,
  'GlobalHomeTeamID': 29,
  'ScoreID': 19054,
  'Status': 'Final',
  'IsClosed': None,
  'DateTimeUTC': '2025-09-06T00:00:00',
  'StadiumDetails': {'StadiumID': 87,
   'Name': 'Arena Corinthians',
   'City': 'Sao Paulo',
   'State': None,
   'Country': 'Brazil',
   'Capacity': 47252,
   'PlayingSurface': 'Grass',
   'GeoLat': -23.54525,
   'GeoLong': -46.474278,
   'Type': 'Outdoor'}},
 {'GameKey': '202510102',
  'SeasonType': 1,
  'Season': 2025,
  'Week': 1,
  'Date': '2025-09-07T13:00:00',
  'AwayTeam': 'TB',
  'HomeTeam': 'ATL',
  'Channel': 'FOX',
  'PointSpread': 0.3,
  'OverUnder': 47.5,
  'StadiumID': 45,
  'Canceled': False,
  'GeoLat': None,
  'GeoLong': None,
  'ForecastTempLow': 66,
  'ForecastTempHigh': 66,
  'ForecastDescription': 'Clear Sky',
  'ForecastWindChill': 66,
  'ForecastWindSpeed': 10,
  'AwayTeamMoneyLine': -83,
  'HomeTeamMoneyLine': -80,
  'Day': '2025-09-07T00:00:00',
  'DateTime': '2025-09-07T13:00:00',
  'GlobalGameID': 19055,
  'GlobalAwayTeamID': 33,
  'GlobalHomeTeamID': 2,
  'ScoreID': 19055,
  'Status': 'Final',
  'IsClosed': None,
  'DateTimeUTC': '2025-09-07T17:00:00',
  'StadiumDetails': {'StadiumID': 45,
   'Name': 'Mercedes-Benz Stadium',
   'City': 'Atlanta',
   'State': 'GA',
   'Country': 'USA',
   'Capacity': 71000,
   'PlayingSurface': 'Artificial',
   'GeoLat': 33.755556,
   'GeoLong': -84.401,
   'Type': 'RetractableDome'}},
 {'GameKey': '202510108',
  'SeasonType': 1,
  'Season': 2025,
  'Week': 1,
  'Date': '2025-09-07T13:00:00',
  'AwayTeam': 'CIN',
  'HomeTeam': 'CLE',
  'Channel': 'FOX',
  'PointSpread': 2.8,
  'OverUnder': 47.5,
  'StadiumID': 6,
  'Canceled': False,
  'GeoLat': None,
  'GeoLong': None,
  'ForecastTempLow': 50,
  'ForecastTempHigh': 50,
  'ForecastDescription': 'Clear Sky',
  'ForecastWindChill': 50,
  'ForecastWindSpeed': 5,
  'AwayTeamMoneyLine': -177,
  'HomeTeamMoneyLine': 148,
  'Day': '2025-09-07T00:00:00',
  'DateTime': '2025-09-07T13:00:00',
  'GlobalGameID': 19056,
  'GlobalAwayTeamID': 7,
  'GlobalHomeTeamID': 8,
  'ScoreID': 19056,
  'Status': 'Final',
  'IsClosed': None,
  'DateTimeUTC': '2025-09-07T17:00:00',
  'StadiumDetails': {'StadiumID': 6,
   'Name': 'Huntington Bank Field',
   'City': 'Cleveland',
   'State': 'OH',
   'Country': 'USA',
   'Capacity': 67431,
   'PlayingSurface': 'Grass',
   'GeoLat': 41.506111,
   'GeoLong': -81.699444,
   'Type': 'Outdoor'}},
 {'GameKey': '202510114',
  'SeasonType': 1,
  'Season': 2025,
  'Week': 1,
  'Date': '2025-09-07T13:00:00',
  'AwayTeam': 'MIA',
  'HomeTeam': 'IND',
  'Channel': 'CBS',
  'PointSpread': -0.7,
  'OverUnder': 46.5,
  'StadiumID': 9,
  'Canceled': False,
  'GeoLat': None,
  'GeoLong': None,
  'ForecastTempLow': 51,
  'ForecastTempHigh': 54,
  'ForecastDescription': 'Clear Sky',
  'ForecastWindChill': 54,
  'ForecastWindSpeed': 5,
  'AwayTeamMoneyLine': -76,
  'HomeTeamMoneyLine': -88,
  'Day': '2025-09-07T00:00:00',
  'DateTime': '2025-09-07T13:00:00',
  'GlobalGameID': 19057,
  'GlobalAwayTeamID': 19,
  'GlobalHomeTeamID': 14,
  'ScoreID': 19057,
  'Status': 'Final',
  'IsClosed': None,
  'DateTimeUTC': '2025-09-07T17:00:00',
  'StadiumDetails': {'StadiumID': 9,
   'Name': 'Lucas Oil Stadium',
   'City': 'Indianapolis',
   'State': 'IN',
   'Country': 'USA',
   'Capacity': 67000,
   'PlayingSurface': 'Artificial',
   'GeoLat': 39.760056,
   'GeoLong': -86.163806,
   'Type': 'RetractableDome'}},
 {'GameKey': '202510115',
  'SeasonType': 1,
  'Season': 2025,
  'Week': 1,
  'Date': '2025-09-07T13:00:00',
  'AwayTeam': 'CAR',
  'HomeTeam': 'JAX',
  'Channel': 'FOX',
  'PointSpread': -3.4,
  'OverUnder': 45.5,
  'StadiumID': 10,
  'Canceled': False,
  'GeoLat': None,
  'GeoLong': None,
  'ForecastTempLow': 75,
  'ForecastTempHigh': 77,
  'ForecastDescription': 'Light Rain',
  'ForecastWindChill': 77,
  'ForecastWindSpeed': 3,
  'AwayTeamMoneyLine': 141,
  'HomeTeamMoneyLine': -168,
  'Day': '2025-09-07T00:00:00',
  'DateTime': '2025-09-07T13:00:00',
  'GlobalGameID': 19058,
  'GlobalAwayTeamID': 5,
  'GlobalHomeTeamID': 15,
  'ScoreID': 19058,
  'Status': 'Final',
  'IsClosed': None,
  'DateTimeUTC': '2025-09-07T17:00:00',
  'StadiumDetails': {'StadiumID': 10,
   'Name': 'EverBank Stadium',
   'City': 'Jacksonville',
   'State': 'FL',
   'Country': 'USA',
   'Capacity': 67814,
   'PlayingSurface': 'Grass',
   'GeoLat': 30.323889,
   'GeoLong': -81.6375,
   'Type': 'Outdoor'}},
 {'GameKey': '202510121',
  'SeasonType': 1,
  'Season': 2025,
  'Week': 1,
  'Date': '2025-09-07T13:00:00',
  'AwayTeam': 'LV',
  'HomeTeam': 'NE',
  'Channel': 'CBS',
  'PointSpread': -1.9,
  'OverUnder': 44.0,
  'StadiumID': 4,
  'Canceled': False,
  'GeoLat': None,
  'GeoLong': None,
  'ForecastTempLow': 57,
  'ForecastTempHigh': 58,
  'ForecastDescription': 'Overcast Clouds',
  'ForecastWindChill': 58,
  'ForecastWindSpeed': 5,
  'AwayTeamMoneyLine': 91,
  'HomeTeamMoneyLine': -108,
  'Day': '2025-09-07T00:00:00',
  'DateTime': '2025-09-07T13:00:00',
  'GlobalGameID': 19059,
  'GlobalAwayTeamID': 25,
  'GlobalHomeTeamID': 21,
  'ScoreID': 19059,
  'Status': 'Final',
  'IsClosed': None,
  'DateTimeUTC': '2025-09-07T17:00:00',
  'StadiumDetails': {'StadiumID': 4,
   'Name': 'Gillette Stadium',
   'City': 'Foxborough',
   'State': 'MA',
   'Country': 'USA',
   'Capacity': 64628,
   'PlayingSurface': 'Artificial',
   'GeoLat': 42.090866,
   'GeoLong': -71.264244,
   'Type': 'Outdoor'}},
 {'GameKey': '202510122',
  'SeasonType': 1,
  'Season': 2025,
  'Week': 1,
  'Date': '2025-09-07T13:00:00',
  'AwayTeam': 'ARI',
  'HomeTeam': 'NO',
  'Channel': 'CBS',
  'PointSpread': 3.4,
  'OverUnder': 44.0,
  'StadiumID': 27,
  'Canceled': False,
  'GeoLat': None,
  'GeoLong': None,
  'ForecastTempLow': 78,
  'ForecastTempHigh': 80,
  'ForecastDescription': 'Scattered Clouds',
  'ForecastWindChill': 80,
  'ForecastWindSpeed': 10,
  'AwayTeamMoneyLine': -212,
  'HomeTeamMoneyLine': 173,
  'Day': '2025-09-07T00:00:00',
  'DateTime': '2025-09-07T13:00:00',
  'GlobalGameID': 19060,
  'GlobalAwayTeamID': 1,
  'GlobalHomeTeamID': 22,
  'ScoreID': 19060,
  'Status': 'Final',
  'IsClosed': None,
  'DateTimeUTC': '2025-09-07T17:00:00',
  'StadiumDetails': {'StadiumID': 27,
   'Name': 'Caesars Superdome',
   'City': 'New Orleans',
   'State': 'LA',
   'Country': 'USA',
   'Capacity': 73208,
   'PlayingSurface': 'Artificial',
   'GeoLat': 29.950833,
   'GeoLong': -90.081111,
   'Type': 'Dome'}},
 {'GameKey': '202510124',
  'SeasonType': 1,
  'Season': 2025,
  'Week': 1,
  'Date': '2025-09-07T13:00:00',
  'AwayTeam': 'PIT',
  'HomeTeam': 'NYJ',
  'Channel': 'CBS',
  'PointSpread': 1.7,
  'OverUnder': 38.0,
  'StadiumID': 3,
  'Canceled': False,
  'GeoLat': None,
  'GeoLong': None,
  'ForecastTempLow': 58,
  'ForecastTempHigh': 61,
  'ForecastDescription': 'Broken Clouds',
  'ForecastWindChill': 61,
  'ForecastWindSpeed': 7,
  'AwayTeamMoneyLine': -126,
  'HomeTeamMoneyLine': 105,
  'Day': '2025-09-07T00:00:00',
  'DateTime': '2025-09-07T13:00:00',
  'GlobalGameID': 19061,
  'GlobalAwayTeamID': 28,
  'GlobalHomeTeamID': 24,
  'ScoreID': 19061,
  'Status': 'Final',
  'IsClosed': None,
  'DateTimeUTC': '2025-09-07T17:00:00',
  'StadiumDetails': {'StadiumID': 3,
   'Name': 'MetLife Stadium',
   'City': 'East Rutherford',
   'State': 'NJ',
   'Country': 'USA',
   'Capacity': 82500,
   'PlayingSurface': 'Artificial',
   'GeoLat': 40.813528,
   'GeoLong': -74.074361,
   'Type': 'Outdoor'}},
 {'GameKey': '202510135',
  'SeasonType': 1,
  'Season': 2025,
  'Week': 1,
  'Date': '2025-09-07T13:00:00',
  'AwayTeam': 'NYG',
  'HomeTeam': 'WAS',
  'Channel': 'FOX',
  'PointSpread': -4.5,
  'OverUnder': 45.5,
  'StadiumID': 19,
  'Canceled': False,
  'GeoLat': None,
  'GeoLong': None,
  'ForecastTempLow': 56,
  'ForecastTempHigh': 58,
  'ForecastDescription': 'Clear Sky',
  'ForecastWindChill': 58,
  'ForecastWindSpeed': 5,
  'AwayTeamMoneyLine': 173,
  'HomeTeamMoneyLine': -209,
  'Day': '2025-09-07T00:00:00',
  'DateTime': '2025-09-07T13:00:00',
  'GlobalGameID': 19062,
  'GlobalAwayTeamID': 23,
  'GlobalHomeTeamID': 35,
  'ScoreID': 19062,
  'Status': 'Final',
  'IsClosed': None,
  'DateTimeUTC': '2025-09-07T17:00:00',
  'StadiumDetails': {'StadiumID': 19,
   'Name': 'Northwest Stadium',
   'City': 'Landover',
   'State': 'MD',
   'Country': 'USA',
   'Capacity': 62000,
   'PlayingSurface': 'Grass',
   'GeoLat': 38.907778,
   'GeoLong': -76.864444,
   'Type': 'Outdoor'}},
 {'GameKey': '202510110',
  'SeasonType': 1,
  'Season': 2025,
  'Week': 1,
  'Date': '2025-09-07T16:05:00',
  'AwayTeam': 'TEN',
  'HomeTeam': 'DEN',
  'Channel': 'FOX',
  'PointSpread': -7.1,
  'OverUnder': 42.5,
  'StadiumID': 13,
  'Canceled': False,
  'GeoLat': None,
  'GeoLong': None,
  'ForecastTempLow': 65,
  'ForecastTempHigh': 68,
  'ForecastDescription': 'Scattered Clouds',
  'ForecastWindChill': 68,
  'ForecastWindSpeed': 3,
  'AwayTeamMoneyLine': 273,
  'HomeTeamMoneyLine': -355,
  'Day': '2025-09-07T00:00:00',
  'DateTime': '2025-09-07T16:05:00',
  'GlobalGameID': 19063,
  'GlobalAwayTeamID': 34,
  'GlobalHomeTeamID': 10,
  'ScoreID': 19063,
  'Status': 'Final',
  'IsClosed': None,
  'DateTimeUTC': '2025-09-07T20:05:00',
  'StadiumDetails': {'StadiumID': 13,
   'Name': 'Empower Field at Mile High',
   'City': 'Denver',
   'State': 'CO',
   'Country': 'USA',
   'Capacity': 76125,
   'PlayingSurface': 'Grass',
   'GeoLat': 39.743889,
   'GeoLong': -105.020097,
   'Type': 'Outdoor'}},
 {'GameKey': '202510130',
  'SeasonType': 1,
  'Season': 2025,
  'Week': 1,
  'Date': '2025-09-07T16:05:00',
  'AwayTeam': 'SF',
  'HomeTeam': 'SEA',
  'Channel': 'FOX',
  'PointSpread': 1.1,
  'OverUnder': 43.5,
  'StadiumID': 31,
  'Canceled': False,
  'GeoLat': None,
  'GeoLong': None,
  'ForecastTempLow': 65,
  'ForecastTempHigh': 65,
  'ForecastDescription': 'Overcast Clouds',
  'ForecastWindChill': 65,
  'ForecastWindSpeed': 3,
  'AwayTeamMoneyLine': -100,
  'HomeTeamMoneyLine': 85,
  'Day': '2025-09-07T00:00:00',
  'DateTime': '2025-09-07T16:05:00',
  'GlobalGameID': 19064,
  'GlobalAwayTeamID': 31,
  'GlobalHomeTeamID': 30,
  'ScoreID': 19064,
  'Status': 'Final',
  'IsClosed': None,
  'DateTimeUTC': '2025-09-07T20:05:00',
  'StadiumDetails': {'StadiumID': 31,
   'Name': 'Lumen Field',
   'City': 'Seattle',
   'State': 'WA',
   'Country': 'USA',
   'Capacity': 68740,
   'PlayingSurface': 'Artificial',
   'GeoLat': 47.5952,
   'GeoLong': -122.331625,
   'Type': 'Outdoor'}},
 {'GameKey': '202510112',
  'SeasonType': 1,
  'Season': 2025,
  'Week': 1,
  'Date': '2025-09-07T16:25:00',
  'AwayTeam': 'DET',
  'HomeTeam': 'GB',
  'Channel': 'CBS',
  'PointSpread': -0.7,
  'OverUnder': 48.0,
  'StadiumID': 22,
  'Canceled': False,
  'GeoLat': None,
  'GeoLong': None,
  'ForecastTempLow': 50,
  'ForecastTempHigh': 50,
  'ForecastDescription': 'Clear Sky',
  'ForecastWindChill': 50,
  'ForecastWindSpeed': 4,
  'AwayTeamMoneyLine': -77,
  'HomeTeamMoneyLine': -88,
  'Day': '2025-09-07T00:00:00',
  'DateTime': '2025-09-07T16:25:00',
  'GlobalGameID': 19065,
  'GlobalAwayTeamID': 11,
  'GlobalHomeTeamID': 12,
  'ScoreID': 19065,
  'Status': 'Final',
  'IsClosed': None,
  'DateTimeUTC': '2025-09-07T20:25:00',
  'StadiumDetails': {'StadiumID': 22,
   'Name': 'Lambeau Field',
   'City': 'Green Bay',
   'State': 'WI',
   'Country': 'USA',
   'Capacity': 81441,
   'PlayingSurface': 'Grass',
   'GeoLat': 44.501389,
   'GeoLong': -88.062222,
   'Type': 'Outdoor'}},
 {'GameKey': '202510132',
  'SeasonType': 1,
  'Season': 2025,
  'Week': 1,
  'Date': '2025-09-07T16:25:00',
  'AwayTeam': 'HOU',
  'HomeTeam': 'LAR',
  'Channel': 'CBS',
  'PointSpread': -2.2,
  'OverUnder': 43.0,
  'StadiumID': 54,
  'Canceled': False,
  'GeoLat': None,
  'GeoLong': None,
  'ForecastTempLow': 71,
  'ForecastTempHigh': 72,
  'ForecastDescription': 'Clear Sky',
  'ForecastWindChill': 72,
  'ForecastWindSpeed': 4,
  'AwayTeamMoneyLine': 109,
  'HomeTeamMoneyLine': -129,
  'Day': '2025-09-07T00:00:00',
  'DateTime': '2025-09-07T16:25:00',
  'GlobalGameID': 19066,
  'GlobalAwayTeamID': 13,
  'GlobalHomeTeamID': 32,
  'ScoreID': 19066,
  'Status': 'Final',
  'IsClosed': None,
  'DateTimeUTC': '2025-09-07T20:25:00',
  'StadiumDetails': {'StadiumID': 54,
   'Name': 'SoFi Stadium',
   'City': 'Inglewood',
   'State': 'CA',
   'Country': 'USA',
   'Capacity': 70240,
   'PlayingSurface': 'Artificial',
   'GeoLat': 33.95345,
   'GeoLong': -118.3392,
   'Type': 'Dome'}},
 {'GameKey': '202510104',
  'SeasonType': 1,
  'Season': 2025,
  'Week': 1,
  'Date': '2025-09-07T20:20:00',
  'AwayTeam': 'BAL',
  'HomeTeam': 'BUF',
  'Channel': 'NBC',
  'PointSpread': 0.8,
  'OverUnder': 51.0,
  'StadiumID': 1,
  'Canceled': False,
  'GeoLat': None,
  'GeoLong': None,
  'ForecastTempLow': 51,
  'ForecastTempHigh': 52,
  'ForecastDescription': 'Broken Clouds',
  'ForecastWindChill': 52,
  'ForecastWindSpeed': 4,
  'AwayTeamMoneyLine': -93,
  'HomeTeamMoneyLine': 78,
  'Day': '2025-09-07T00:00:00',
  'DateTime': '2025-09-07T20:20:00',
  'GlobalGameID': 19067,
  'GlobalAwayTeamID': 3,
  'GlobalHomeTeamID': 4,
  'ScoreID': 19067,
  'Status': 'Final',
  'IsClosed': None,
  'DateTimeUTC': '2025-09-08T00:20:00',
  'StadiumDetails': {'StadiumID': 1,
   'Name': 'Highmark Stadium',
   'City': 'Orchard Park',
   'State': 'NY',
   'Country': 'USA',
   'Capacity': 71608,
   'PlayingSurface': 'Artificial',
   'GeoLat': 42.773758,
   'GeoLong': -78.786837,
   'Type': 'Outdoor'}},
 {'GameKey': '202510106',
  'SeasonType': 1,
  'Season': 2025,
  'Week': 1,
  'Date': '2025-09-08T20:15:00',
  'AwayTeam': 'MIN',
  'HomeTeam': 'CHI',
  'Channel': 'ABC',
  'PointSpread': 0.3,
  'OverUnder': 43.5,
  'StadiumID': 20,
  'Canceled': False,
  'GeoLat': None,
  'GeoLong': None,
  'ForecastTempLow': 71,
  'ForecastTempHigh': 72,
  'ForecastDescription': 'Clear Sky',
  'ForecastWindChill': 71,
  'ForecastWindSpeed': 6,
  'AwayTeamMoneyLine': -82,
  'HomeTeamMoneyLine': -82,
  'Day': '2025-09-08T00:00:00',
  'DateTime': '2025-09-08T20:15:00',
  'GlobalGameID': 19068,
  'GlobalAwayTeamID': 20,
  'GlobalHomeTeamID': 6,
  'ScoreID': 19068,
  'Status': 'Final',
  'IsClosed': None,
  'DateTimeUTC': '2025-09-09T00:15:00',
  'StadiumDetails': {'StadiumID': 20,
   'Name': 'Soldier Field',
   'City': 'Chicago',
   'State': 'IL',
   'Country': 'USA',
   'Capacity': 61500,
   'PlayingSurface': 'Grass',
   'GeoLat': 41.86232,
   'GeoLong': -87.616699,
   'Type': 'Outdoor'}},
 {'GameKey': '202510212',
  'SeasonType': 1,
  'Season': 2025,
  'Week': 2,
  'Date': '2025-09-11T20:15:00',
  'AwayTeam': 'WAS',
  'HomeTeam': 'GB',
  'Channel': 'AMZN',
  'PointSpread': -2.2,
  'OverUnder': 48.5,
  'StadiumID': 22,
  'Canceled': False,
  'GeoLat': None,
  'GeoLong': None,
  'ForecastTempLow': 57,
  'ForecastTempHigh': 60,
  'ForecastDescription': 'Few Clouds',
  'ForecastWindChill': 57,
  'ForecastWindSpeed': 1,
  'AwayTeamMoneyLine': 113,
  'HomeTeamMoneyLine': -133,
  'Day': '2025-09-11T00:00:00',
  'DateTime': '2025-09-11T20:15:00',
  'GlobalGameID': 19083,
  'GlobalAwayTeamID': 35,
  'GlobalHomeTeamID': 12,
  'ScoreID': 19083,
  'Status': 'Final',
  'IsClosed': None,
  'DateTimeUTC': '2025-09-12T00:15:00',
  'StadiumDetails': {'StadiumID': 22,
   'Name': 'Lambeau Field',
   'City': 'Green Bay',
   'State': 'WI',
   'Country': 'USA',
   'Capacity': 81441,
   'PlayingSurface': 'Grass',
   'GeoLat': 44.501389,
   'GeoLong': -88.062222,
   'Type': 'Outdoor'}},
 {'GameKey': '202510203',
  'SeasonType': 1,
  'Season': 2025,
  'Week': 2,
  'Date': '2025-09-14T13:00:00',
  'AwayTeam': 'CLE',
  'HomeTeam': 'BAL',
  'Channel': 'CBS',
  'PointSpread': -9.4,
  'OverUnder': 46.5,
  'StadiumID': 7,
  'Canceled': False,
  'GeoLat': None,
  'GeoLong': None,
  'ForecastTempLow': 66,
  'ForecastTempHigh': 68,
  'ForecastDescription': 'Scattered Clouds',
  'ForecastWindChill': 68,
  'ForecastWindSpeed': 4,
  'AwayTeamMoneyLine': 438,
  'HomeTeamMoneyLine': -641,
  'Day': '2025-09-14T00:00:00',
  'DateTime': '2025-09-14T13:00:00',
  'GlobalGameID': 19084,
  'GlobalAwayTeamID': 8,
  'GlobalHomeTeamID': 3,
  'ScoreID': 19084,
  'Status': 'Final',
  'IsClosed': None,
  'DateTimeUTC': '2025-09-14T17:00:00',
  'StadiumDetails': {'StadiumID': 7,
   'Name': 'M&T Bank Stadium',
   'City': 'Baltimore',
   'State': 'MD',
   'Country': 'USA',
   'Capacity': 71008,
   'PlayingSurface': 'Grass',
   'GeoLat': 39.278056,
   'GeoLong': -76.622778,
   'Type': 'Outdoor'}},
 {'GameKey': '202510207',
  'SeasonType': 1,
  'Season': 2025,
  'Week': 2,
  'Date': '2025-09-14T13:00:00',
  'AwayTeam': 'JAX',
  'HomeTeam': 'CIN',
  'Channel': 'CBS',
  'PointSpread': -2.6,
  'OverUnder': 49.0,
  'StadiumID': 5,
  'Canceled': False,
  'GeoLat': None,
  'GeoLong': None,
  'ForecastTempLow': 64,
  'ForecastTempHigh': 70,
  'ForecastDescription': 'Clear Sky',
  'ForecastWindChill': 70,
  'ForecastWindSpeed': 3,
  'AwayTeamMoneyLine': 119,
  'HomeTeamMoneyLine': -141,
  'Day': '2025-09-14T00:00:00',
  'DateTime': '2025-09-14T13:00:00',
  'GlobalGameID': 19085,
  'GlobalAwayTeamID': 15,
  'GlobalHomeTeamID': 7,
  'ScoreID': 19085,
  'Status': 'Final',
  'IsClosed': None,
  'DateTimeUTC': '2025-09-14T17:00:00',
  'StadiumDetails': {'StadiumID': 5,
   'Name': 'Paycor Stadium',
   'City': 'Cincinnati',
   'State': 'OH',
   'Country': 'USA',
   'Capacity': 65515,
   'PlayingSurface': 'Artificial',
   'GeoLat': 39.095309,
   'GeoLong': -84.516003,
   'Type': 'Outdoor'}},
 {'GameKey': '202510209',
  'SeasonType': 1,
  'Season': 2025,
  'Week': 2,
  'Date': '2025-09-14T13:00:00',
  'AwayTeam': 'NYG',
  'HomeTeam': 'DAL',
  'Channel': 'FOX',
  'PointSpread': -4.1,
  'OverUnder': 44.5,
  'StadiumID': 17,
  'Canceled': False,
  'GeoLat': None,
  'GeoLong': None,
  'ForecastTempLow': 79,
  'ForecastTempHigh': 81,
  'ForecastDescription': 'Scattered Clouds',
  'ForecastWindChill': 81,
  'ForecastWindSpeed': 6,
  'AwayTeamMoneyLine': 150,
  'HomeTeamMoneyLine': -180,
  'Day': '2025-09-14T00:00:00',
  'DateTime': '2025-09-14T13:00:00',
  'GlobalGameID': 19086,
  'GlobalAwayTeamID': 23,
  'GlobalHomeTeamID': 9,
  'ScoreID': 19086,
  'Status': 'F/OT',
  'IsClosed': None,
  'DateTimeUTC': '2025-09-14T17:00:00',
  'StadiumDetails': {'StadiumID': 17,
   'Name': 'AT&T Stadium',
   'City': 'Arlington',
   'State': 'TX',
   'Country': 'USA',
   'Capacity': 80000,
   'PlayingSurface': 'Artificial',
   'GeoLat': 32.747778,
   'GeoLong': -97.092778,

In [ ]:
# Flatten the json structure to break out the nested dictionaries and make it callable to pd.DataFrame
data = pd.json_normalize(data)

In [ ]:
# Creating the df and pulling files from json 
schedules = pd.DataFrame(data)[["GameKey", "Week", "Date", "AwayTeam", "HomeTeam", "PointSpread", "OverUnder", "StadiumID", "AwayTeamMoneyLine",
                                 "HomeTeamMoneyLine", "GlobalAwayTeamID", "GlobalHomeTeamID","StadiumDetails.Name", "StadiumDetails.City", "StadiumDetails.Country",
                                   "StadiumDetails.Capacity", "StadiumDetails.PlayingSurface", "StadiumDetails.Type"]]

In [28]:
schedules.head()

,GameKey,Week,Date,AwayTeam,HomeTeam,PointSpread,OverUnder,StadiumID,AwayTeamMoneyLine,HomeTeamMoneyLine,GlobalAwayTeamID,GlobalHomeTeamID,StadiumDetails.Name,StadiumDetails.City,StadiumDetails.Country,StadiumDetails.Capacity,StadiumDetails.PlayingSurface,StadiumDetails.Type
0,202510126,1,2025-09-04T20:20:00,DAL,PHI,-6.0,47.5,18.0,260.0,-328.0,9,26,Lincoln Financial Field,Philadelphia,USA,67594.0,Grass,Outdoor
1,202510129,1,2025-09-05T20:00:00,KC,LAC,1.7,47.5,87.0,-131.0,111.0,16,29,Arena Corinthians,Sao Paulo,Brazil,47252.0,Grass,Outdoor
2,202510102,1,2025-09-07T13:00:00,TB,ATL,0.3,47.5,45.0,-83.0,-80.0,33,2,Mercedes-Benz Stadium,Atlanta,USA,71000.0,Artificial,RetractableDome
3,202510108,1,2025-09-07T13:00:00,CIN,CLE,2.8,47.5,6.0,-177.0,148.0,7,8,Huntington Bank Field,Cleveland,USA,67431.0,Grass,Outdoor
4,202510114,1,2025-09-07T13:00:00,MIA,IND,-0.7,46.5,9.0,-76.0,-88.0,19,14,Lucas Oil Stadium,Indianapolis,USA,67000.0,Artificial,RetractableDome

In [29]:
scores_bets.head()

,schedule_date,schedule_season,schedule_week,schedule_playoff,team_home,score_home,score_away,team_away,team_favorite_id,spread_favorite,over_under_line,stadium,stadium_neutral,weather_temperature,weather_wind_mph,weather_humidity,weather_detail
0,9/2/1966,1966,1,False,Miami Dolphins,14.0,23.0,Oakland Raiders,NaN,NaN,NaN,Orange Bowl,False,83.0,6.0,71.0,NaN
1,9/3/1966,1966,1,False,Houston Oilers,45.0,7.0,Denver Broncos,NaN,NaN,NaN,Rice Stadium,False,81.0,7.0,70.0,NaN
2,9/4/1966,1966,1,False,San Diego Chargers,27.0,7.0,Buffalo Bills,NaN,NaN,NaN,Balboa Stadium,False,70.0,7.0,82.0,NaN
3,9/9/1966,1966,2,False,Miami Dolphins,14.0,19.0,New York Jets,NaN,NaN,NaN,Orange Bowl,False,82.0,11.0,78.0,NaN
4,9/10/1966,1966,1,False,Green Bay Packers,24.0,3.0,Baltimore Colts,NaN,NaN,NaN,Lambeau Field,False,64.0,8.0,62.0,NaN

In [30]:
scores_bets = scores_bets[scores_bets["schedule_season"] >= 2005]

In [32]:
scores_bets.head()

,schedule_date,schedule_season,schedule_week,schedule_playoff,team_home,score_home,score_away,team_away,team_favorite_id,spread_favorite,over_under_line,stadium,stadium_neutral,weather_temperature,weather_wind_mph,weather_humidity,weather_detail
8673,9/8/2005,2005,1,False,New England Patriots,30.0,20.0,Oakland Raiders,NE,-7.5,50,Gillette Stadium,False,71.0,9.0,64.0,NaN
8674,9/11/2005,2005,1,False,Baltimore Ravens,7.0,24.0,Indianapolis Colts,IND,-3.0,47,M&T Bank Stadium,False,69.0,4.0,63.0,NaN
8675,9/11/2005,2005,1,False,Buffalo Bills,22.0,7.0,Houston Texans,BUF,-4.5,39,Ralph Wilson Stadium,False,64.0,8.0,58.0,NaN
8676,9/11/2005,2005,1,False,Carolina Panthers,20.0,23.0,New Orleans Saints,CAR,-6.5,45.5,Bank of America Stadium,False,74.0,12.0,49.0,NaN
8677,9/11/2005,2005,1,False,Cleveland Browns,13.0,27.0,Cincinnati Bengals,CIN,-3.5,44.5,FirstEnergy Stadium,False,69.0,6.0,63.0,NaN

In [35]:
scores_bets["team_home"].nunique()

37